# Generated by stackage2nix 0.7.2 from "/home/ttuegel/lts-haskell/lts-12.21.yaml"
{ callPackage, buildPackages, pkgs, stdenv, lib
, overrides ? (self: super: {})
, packageSetConfig ? (self: super: {})
}:

let
  inherit (lib) extends fold makeExtensible;
  haskellLib = pkgs.haskell.lib;
  inherit (haskellLib) makePackageSet;

  pkgsHaskellModules = pkgs.path + "/pkgs/development/haskell-modules";

  haskellPackages =
    pkgs.callPackage makePackageSet {
      ghc = buildPackages.haskell.compiler.ghc844;
      buildHaskellPackages = buildPackages.haskell.packages.ghc844;
      package-set = import ./packages.nix;
      inherit stdenv haskellLib extensible-self;
    };

  compilerConfig =
    import  ./configuration-packages.nix {
      inherit pkgs haskellLib;
    };

  configurationCommon =
    if builtins.pathExists ./configuration-common.nix
    then import ./configuration-common.nix { inherit pkgs haskellLib; }
    else self: super: {};

  configurationNix =
    import (pkgsHaskellModules + "/configuration-nix.nix") {
      inherit pkgs haskellLib;
    };

  configurationGHC =
    import (pkgsHaskellModules + "/configuration-ghc-8.4.x.nix") {
      inherit pkgs haskellLib;
    };

  extensible-self =
    makeExtensible
    (fold extends haskellPackages
      [
        overrides
        configurationCommon
        packageSetConfig
        compilerConfig
        configurationGHC
        configurationNix
      ]
    );

in extensible-self
